### ISSUE TITLE
🐛 Bug Report: Missing `.env.example`

### ISSUE THREAD

**Issue by getdir** [appwrite/demo-todo-with-nextjs#13]
### 👟 Reproduction steps

.env.example not present as README instructs

### 👍 Expected behavior

commit example

### 👎 Actual Behavior

no example

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@getdir thanks for raising this issue! 🙏🏼 

@codercatdev what should be in `.env.example`?
